name: CI/CD Pipeline by Fortress Technologies Inc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: "17"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push accounts-db
        working-directory: src/accounts/accounts-db
        run: |
          docker build -t iscanprint/accounts-dbbankapp:2.0 .
          docker push iscanprint/accounts-dbbankapp:2.0

      - name: Build and push contacts
        working-directory: src/accounts/contacts
        run: |
          docker build -t iscanprint/contactsbankapp:2.0 .
          docker push iscanprint/contactsbankapp:2.0

      - name: Build and push userservice
        working-directory: src/accounts/userservice
        run: |
          docker build -t iscanprint/userservicebankapp:2.0 .
          docker push iscanprint/userservicebankapp:2.0

      - name: Build and push frontend
        working-directory: src/frontend
        run: |
          docker build -t iscanprint/frontendbankapp:2.0 .
          docker push iscanprint/frontendbankapp:2.0

      - name: Build and push ledger-db
        working-directory: src/ledger/ledger-db
        run: |
          docker build -t iscanprint/ledger-dbbankapp:2.0 .
          docker push iscanprint/ledger-dbbankapp:2.0

      - name: Build and push loadgenerator
        working-directory: src/loadgenerator
        run: |
          docker build -t iscanprint/loadgeneratorbankapp:2.0 .
          docker push iscanprint/loadgeneratorbankapp:2.0

      - name: Build and push ledgermonolith
        working-directory: src/ledgermonolith
        run: |
          mvn package -DskipTests=true
          docker build -t iscanprint/ledgermonolithbankapp:2.0 .
          docker push iscanprint/ledgermonolithbankapp:2.0
